### ISSUE TITLE
Repeated email sent for some Notices

### ISSUE THREAD

**Issue by DefCon-007** [metakgp/mftp#22]
Some notices are sent repeatedly.

**Comment by kaustubhhiware** [comment]
Correct me if I'm wrong, but seems to me that whenever an existing notice is updated, another mail is sent out. Sometimes, there are no edits made, yet mails are sent out, creating the impression of repeated mails.

I'm speculating here, someone with Placecomm friends/experience could guide us here.

**Comment by amrav** [comment]
There shouldn't be literally no change - at least one character should have been changed, or maybe the attachment was updated. The characters might be invisible (eg html). 

In general we err on the side of sending too many rather than too few updates, but one way to diagnose this is to check the logs for the notice that seems duplicated and verify that the text and attachment md5 are exactly the same.

**Comment by kaustubhhiware** [comment]
(03-11-2018 13:21):

Almost all notices seem to have a date in them. Would it suffice to check if the notice is posted within the last 2-3 hours, before sending the mail via the bot ?

This will handle the kind of repeated mails: `Notice: Schedule - Goldman Sachs` sent out at 
Sun 4 Nov, 23:39.

**Comment by amrav** [comment]
New emails are only sent out if something in the text or attachment
changed. You could check the logs to see what was changed - it might not be
very obvious otherwise.

As long as this is the behaviour, we should err on the side of sending too
many emails rather than too few.

The date is not reliable, and not always updated when the notice is updated.

**Comment by amrav** [comment]
@kaustabhhiware in the particular case you're talking about, the second email has a modified attachment and the third email has the attachment removed
