### ISSUE TITLE
[Discussion] How to communicate type to the user, using Subject / From header?

### ISSUE THREAD

**Issue by icyflame** [metakgp/mftp#7]
https://github.com/metakgp/mftp/blob/master/update.py#L49

The data needs to be extracted from the `Text` portion of the message which is inside `notice['text']`.The data is in HTML markup as:

`<b>Type</b> : PLACEMENT` or `<b>Type</b> : INTERNSHIP`.

@zorroblue @DefCon-007 I am sure this is easy. See if you can put it together really quickly. I will be off trying to get this out of BS4 meanwhile.

**Comment by amrav** [comment]
Please describe the rationale when asking for a new feature. That allows
people not familiar with this issue to understand better what you're trying
to do.

I would be quite wary of changing the email format sent by MFTP. It's not
pretty, but one major advantage is that it corresponds pretty well to what
you see on the noticeboard. Breaking that 1-1 correspondence by recombining
different fields could be confusing or misleading if it breaks on some
input. That's why the original format was as stupid as possible.

Have you considered whether what you're trying to achieve is 1) a real need
for most users 2) difficult to achieve through less complex means like
email filters?

**Comment by icyflame** [comment]
@amrav Yes, sorry. The discussion didn't happen, but the thing that me and Vivek. Yes, indeed, it can be definitely achieved with email filters. I will move this into discussion. Sorry about the wrong classification :)

**Comment by icyflame** [comment]
@amrav Yes, sorry about this.
Email filters would certainly do a better job, then, we should change the from header depending on what type of notice it is. (say `mftp-placement@metakgp.org` and `mftp-internship@metakgp.org`)
I am moving this into discussion. Sorry about the mis-classification.

cc @vivekiitkgp @nevinvalsaraj

**Comment by vivekiitkgp** [comment]
One point in favor of nothing doing this is that we do not know when the format could change. Without exhaustive testing there might be cases which break the experience. In such a case, neither of the solution (email filters vs subject header) works.

> is 1) a real need for most users

It's slightly non-trivial to assess. So far, we have had no complaints or requests from people using MFTP, so it is safe to assume that they are okay with it. Whether they'd like this modification or not is a different question, and I don't know the answer to it. I know, I would.

**Comment by amrav** [comment]
> Email filters would certainly do a better job, then, we should change the from header depending on what type of notice it is. (say mftp-placement@metakgp.org and mftp-internship@metakgp.org)

Why not just have an email filter that looks for "Type : INTERNSHIP" in the email body?

> Without exhaustive testing there might be cases which break the experience. In such a case, neither of the solution (email filters vs subject header) works.

I think a user set filter breaking because the format of the email changes is less bad than mftp's guarantees breaking. When a user looks at an mftp email, they know they're looking at whatever was posted, and that is the only guarantee mftp currently has to provide. Whereas if we start making assumptions about the format, and tomorrow the user receives an email that says "[Internship] Blah blah" in the subject when actually it's not, that's really bad.

**Comment by icyflame** [comment]
@amrav Yeah, that filter works :smile: I just tested it. The user can set it up, if they are so inclined. And this will break if the format changes, but it won't be too bad as chances of `Type: PLACEMENT` being in an email that relates to internship is remote.

Lesson: _Don't reinvent the wheel_. Point taken! 

Thanks for the feedback @vivekiitkgp.
